# Generated by Django 5.1.4 on 2024-12-19 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scorecards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='APR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='BrandingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='LineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='PromoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.feetype')),
            ],
        ),
        migrations.CreateModel(
            name='CreditLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tier', models.CharField(max_length=2)),
                ('linetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.linetype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'deactivated'), (1, 'active'), (2, 'awaiting approval'), (3, 'awaiting activation'), (4, 'rejected')])),
                ('creationdate', models.DateField()),
                ('approvaldate', models.DateField()),
                ('activationdate', models.DateField()),
                ('rejectiondate', models.DateField()),
                ('deactivationdate', models.DateField()),
                ('applicationprocess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.applicationprocess')),
                ('brandingcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.brandingcode')),
                ('feetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.feetype')),
                ('linetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.linetype')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecards.scorecard')),
                ('promotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.promotype')),
            ],
        ),
        migrations.CreateModel(
            name='ActiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandingcode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.brandingcode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.product')),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=16)),
                ('promotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.promotype')),
            ],
        ),
        migrations.AddField(
            model_name='brandingcode',
            name='retailer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.retailer'),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.apr')),
                ('creditlimit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.creditline')),
                ('fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.fee')),
                ('mdr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.discount')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecards.scorecard')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecards.scorecardtier')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.product')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailersettings.promo')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'tier'), name='unique_product_tier')],
            },
        ),
    ]
