# Generated by Django 5.1.4 on 2024-12-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailersettings', '0002_activeproduct_name_apr_name_creditline_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeproduct',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
