# Generated by Django 5.1.4 on 2024-12-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailersettings', '0003_alter_activeproduct_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='activationdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='approvaldate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='deactivationdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rejectiondate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
