# Generated by Django 5.1.4 on 2024-12-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailersettings', '0004_alter_product_activationdate_and_more'),
        ('scorecards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='loan',
            name='unique_product_tier',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='tier',
            new_name='scorecardtier',
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(fields=('product', 'scorecardtier'), name='unique_product_scorecardtier'),
        ),
    ]
