# Generated by Django 5.1.4 on 2024-12-21 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailersettings', '0005_remove_loan_unique_product_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingcode',
            name='activeproduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activeproduct', to='retailersettings.product'),
        ),
        migrations.DeleteModel(
            name='ActiveProduct',
        ),
    ]
