# Generated by Django 5.1.4 on 2024-12-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailersettings', '0006_brandingcode_activeproduct_delete_activeproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.IntegerField(choices=[('DAD', 'deactivated'), ('ACT', 'active'), ('AWP', 'awaiting approval'), ('AWA', 'awaiting activation'), ('RJT', 'rejected')]),
        ),
    ]
