# Generated by Django 5.1.4 on 2024-12-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailersettings', '0007_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='state',
            field=models.CharField(choices=[('DAD', 'deactivated'), ('ACT', 'active'), ('AWP', 'awaiting approval'), ('AWA', 'awaiting activation'), ('RJT', 'rejected')], max_length=3),
        ),
    ]
