# Generated by Django 5.1.4 on 2024-12-23 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retailersettings', '0008_alter_product_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingcode',
            name='activeproduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activeproduct', to='retailersettings.product'),
        ),
    ]
